WINDOWS_TERMINAL_CFG="/mnt/c/Users/paulo/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
import_zsh:
	cp ../.zshrc ~/.zshrc
	cp .platform ~/.platform
export_zsh:
	cp ~/.zshrc ../.zshrc
	cp ~/.platform .platform
uncap_setup:
	echo "TODO"
import_terminal_cfg:
	cp $(WINDOWS_TERMINAL_CFG) .
export_terminal_cfg:
	cp settings.json $(WINDOWS_TERMINAL_CFG)
